testing: add NO_DOCKER environment variable to skip image building (bug 1287890); r=rwood
If NO_DOCKER is set, we won't attempt to build Docker images.

This variable can be set in the Jenkins test environment to make the
"no Docker" test environment start faster.

MozReview-Commit-ID: 3C3rTYcWJjj

--HG--
extra : amend_source : c25f373620d747ccb270a13eb9089e95aff350d7

diff --git a/create-test-environment b/create-test-environment
--- a/create-test-environment
+++ b/create-test-environment
@@ -221,16 +221,20 @@ fi
 
 git -C venv/git-cinnabar pull
 
-echo ""
-echo "Building Docker images."
-echo "This could take a while and may consume a lot of internet bandwidth."
-echo "If you don't want Docker images, it is safe to hit CTRL+c to abort this."
+if [ -z "${NO_DOCKER}" ]; then
+  echo ""
+  echo "Building Docker images."
+  echo "This could take a while and may consume a lot of internet bandwidth."
+  echo "If you don't want Docker images, it is safe to hit CTRL+c to abort this."
 
-./d0cker build-all $FORKS || {
-  echo "You will not be able to run tests that require Docker.";
-  echo "Please see https://docs.docker.com/installation/ for how to install Docker.";
-  echo "When Docker is installed, re-run this script";
-  exit 1
-}
+  ./d0cker build-all $FORKS || {
+    echo "You will not be able to run tests that require Docker.";
+    echo "Please see https://docs.docker.com/installation/ for how to install Docker.";
+    echo "When Docker is installed, re-run this script";
+    exit 1
+  }
+else
+  echo "Not building Docker images because NO_DOCKER is set."
+fi
 
 echo finished creating test environment
