bug 1268653 - fail noisily!
Set bash flags to immediately stop on error, providing context to user.

--HG--
extra : rebase_source : 9a50b8522fc41fca7eaf9def54b2994e9baa93f2

diff --git a/create-deploy-environment b/create-deploy-environment
--- a/create-deploy-environment
+++ b/create-deploy-environment
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+# Bail on any setup error
+set -eu
 
 ROOT=`pwd`
 VENV=${ROOT}/venv
@@ -26,8 +28,13 @@ if [ ! -d ${VENV} ]; then
   cd ${ROOT}
 fi
 
+# activate fails on read of PS1, which doesn't exist in non-interactive shell
+set +u
 source ${VENV}/bin/activate
+set -u
 
+# Note: pycrypto may not build on OSX with hombrew gmp unless you add:
+# export CFLAGS='-I/usr/local/include -L/usr/local/lib'
 pip install --upgrade --require-hashes -r deploy-requirements.txt
 
 cd testing
