testing: install a Py3 interpreter and Mercurial executables in test environment (Bug 1541166) r=glob
This commit teaches `create-test-environment` to install a Python 3
interpreter in the `venv/` directory created by the script. We
introduce new `test-requirements-3.{in,txt}` files which are
installed into the interpreter after creation. These new files are
derived from `test-requirements.{in,txt}` and include all packages
necessary to run tests for v-c-t. The command assumes the user has
`python3` aliased to a Python 3 interpreter in their shell.

The main use case for this change is to enabled running tests against
Python 3 Mercurial installations, like so:

  $ ./run-tests hgserver/ --with-hg=venv/py3/mercurials/5.2rc0/bin/hg

Support for `--all-hg-versions` will be added in a later commit.
Targetting specific versions of Python can be achieved by aliasing
`python3` to the desired interpreter in the users shell.

Differential Revision: https://phabricator.services.mozilla.com/D51735

--HG--
extra : moz-landing-system : lando

diff --git a/create-test-environment b/create-test-environment
--- a/create-test-environment
+++ b/create-test-environment
@@ -16,79 +16,92 @@ if [ "$sslcheck" -ne 0 ]; then
 fi
 
 ROOT=`pwd`
+
+for PYTHON_VERSION_NUMBER in 2 3
+do
+    echo "Installing virtualenv for Python ${PYTHON_VERSION_NUMBER}"
+
+    # Set environment variables according to Python version being installed
+    if [[ ${PYTHON_VERSION_NUMBER} -eq 2 ]]
+    then
+        VENV=${ROOT}/venv
+        PYTHON_VERSION=python2.7
+    else
+        VENV=${ROOT}/venv/py3
+        PYTHON_VERSION=python3.6
+    fi
+
+    if [ ! -d ${VENV}/lib ]; then
+      # There is a bug in pycrypto where it tries to invoke `configure` instead
+      # of a path qualified configure. So if there is a "configure" on $PATH
+      # it will invoke the wrong one.
+      configure=which configure &>/dev/null || true
+      if [ "x" != "x${configure}" ]; then
+        echo "configure in PATH; pycrypto install will fail!"
+        echo "Remove the path containing ${configure} from PATH"
+        exit 1
+      fi
+
+      . ${ROOT}/testing/create-virtualenv
+    fi
+
+    cd ${ROOT}
+    source ${VENV}/bin/activate
+
+    # Install different test requirements into each venv
+    if [[ ${PYTHON_VERSION_NUMBER} -eq 2 ]]
+    then
+        pip install --upgrade --require-hashes -r test-requirements.txt
+    else
+        HGPYTHON3=1 pip install --upgrade --require-hashes -r test-requirements-3.txt
+    fi
+
+
+    cd hgserver/hgmolib
+    python setup.py develop
+    cd ../..
+
+    cd pylib/Bugsy
+    python setup.py develop
+    cd ../..
+
+    cd pylib/mozansible
+    python setup.py develop
+    cd ../..
+
+    cd pylib/mozhg
+    python setup.py develop
+    cd ../..
+
+    cd pylib/mozhginfo
+    python setup.py develop
+    cd ../..
+
+    cd pylib/mozautomation
+    python setup.py develop
+    cd ../..
+
+    cd pylib/vcsreplicator
+    python setup.py develop
+    cd ../..
+
+    cd hghooks
+    python setup.py develop
+    cd ..
+
+    cd testing
+    python setup.py develop
+    cd ..
+
+done
+
+
+python -m vcttesting.environment install-mercurials
+
+# Set venv back to Python 2 for test runner code
 VENV=${ROOT}/venv
-
-if [ ! -d ${VENV}/lib ]; then
-  # There is a bug in pycrypto where it tries to invoke `configure` instead
-  # of a path qualified configure. So if there is a "configure" on $PATH
-  # it will invoke the wrong one.
-  configure=which configure &>/dev/null || true
-  if [ "x" != "x${configure}" ]; then
-    echo "configure in PATH; pycrypto install will fail!"
-    echo "Remove the path containing ${configure} from PATH"
-    exit 1
-  fi
-
-  . ${ROOT}/testing/create-virtualenv
-fi
-
-cd ${ROOT}
 source ${VENV}/bin/activate
 
-pip install --upgrade --require-hashes -r test-requirements.txt
-
-cd hgserver/hgmolib
-python setup.py develop
-cd ../..
-
-cd pylib/Bugsy
-python setup.py develop
-cd ../..
-
-cd pylib/mozansible
-python setup.py develop
-cd ../..
-
-cd pylib/mozhg
-python setup.py develop
-cd ../..
-
-cd pylib/mozhginfo
-python setup.py develop
-cd ../..
-
-cd pylib/mozautomation
-python setup.py develop
-cd ../..
-
-cd pylib/vcsreplicator
-python setup.py develop
-cd ../..
-
-cd hghooks
-python setup.py develop
-cd ..
-
-cd testing
-python setup.py develop
-cd ..
-
-# Collect code coverage from all Python processes if environment variable
-# is set.
-cat > venv/bin/sitecustomize.py << EOF
-import os
-
-if os.environ.get('CODE_COVERAGE', False):
-    import uuid
-    import coverage
-
-    covpath = os.path.join(os.environ['COVERAGE_DIR'],
-        'coverage.%s' % uuid.uuid1())
-    cov = coverage.coverage(data_file=covpath, auto_data=True)
-    cov._warn_no_data = False
-    cov._warn_unimported_source = False
-    cov.start()
-EOF
 
 python -m vcttesting.environment install-mercurials
 
